apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pethospital
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AnandarajuCS/pethospital.git
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: pethospital-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
