apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pet-service.yaml
  - hospital-service.yaml
  - doctor-service.yaml
  - frontend.yaml

namespace: pethospital-dev

commonLabels:
  app.kubernetes.io/part-of: pet-hospital
  app.kubernetes.io/managed-by: kustomize
