apiVersion: v1
kind: Service
metadata:
  name: pet-service
  labels:
    app: pet-service
spec:
  selector:
    app: pet-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-service
  labels:
    app: pet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-service
  template:
    metadata:
      labels:
        app: pet-service
    spec:
      containers:
        - name: pet-service
          image: 304930966996.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-pet-service:5a87a15292bd85d2a951a0b1d7220adaf1887e95
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ecr-registry-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pet-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pet-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
