apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
  namespace: pethospital-dev
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "PLACEHOLDER_REGISTRY": {
          "auth": "PLACEHOLDER_AUTH"
        }
      }
    }
