apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
  namespace: pethospital-dev
type: kubernetes.io/dockerconfigjson
data:
  # This is a placeholder that will be replaced by the actual credentials in the GitHub workflow
  .dockerconfigjson: eyJhdXRocyI6eyI2MjIwMzc2NjQzMTUuZGtyLmVjci51cy13ZXN0LTIuYW1hem9uYXdzLmNvbSI6eyJhdXRoIjoiUVZkVE9rVkRVaUJRUVZOVFYwOVNSQT09In19fQ==
