apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ecr-secret.yaml

namespace: pethospital-dev

replicas:
  - name: pet-service
    count: 2
  - name: hospital-service
    count: 2
  - name: doctor-service
    count: 2
  - name: frontend
    count: 2

configMapGenerator:
  - name: pethospital-config
    literals:
      - ENVIRONMENT=dev

# Use specific image names instead of placeholders
images:
  - name: ${ECR_REPOSITORY_URL}/pet-service
    newName: 622037664315.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-pet-service
    newTag: latest
  - name: ${ECR_REPOSITORY_URL}/hospital-service
    newName: 622037664315.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-hospital-service
    newTag: latest
  - name: ${ECR_REPOSITORY_URL}/doctor-service
    newName: 622037664315.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-doctor-service
    newTag: latest
  - name: ${ECR_REPOSITORY_URL}/frontend
    newName: 622037664315.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-frontend
    newTag: latest

patchesStrategicMerge:
  - patches/deployment-patches.yaml
