apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: pethospital-dev

replicas:
  - name: pet-service
    count: 2
  - name: hospital-service
    count: 2
  - name: doctor-service
    count: 2
  - name: frontend
    count: 2

configMapGenerator:
  - name: pethospital-config
    literals:
      - ENVIRONMENT=dev

patchesStrategicMerge:
  - patches/deployment-patches.yaml
